/* One page per project, all served by case.html?p=<slug>. The index entry
 * (title, caption, tags, links, status) comes from `projects` in script.js;
 * this file adds the write-up: a few short sections and the fact list.
 *
 * Slugs are made from the title (see slugFor in script.js). A project with no
 * entry here still gets a page - caption, picture, links - just no prose.
 */

const CASES = {
  "shellfall": {
    picture: "Day one of the campaign: the guns are laid, the first flotilla is in range.",
    sections: [
      ["What it is", "A coastal-defence game. You hold a fortress against a campaign of named capital ships; you place the guns yourself, mark what to hit, and the enemy keeps sailing. Released on itch.io under the name Penumbra."],
      ["How it is built", "Python and pygame, with the ships, the fortress and the sea drawn as sprites and the campaign scripted as a sequence of named engagements. A field manual inside the game explains the guns; a field-commands screen lets you give orders between salvos."],
      ["What it taught", "Pacing. The first builds let you fire as fast as you could click and the whole thing collapsed into noise; the reload timers and the named ships are what turned it into a game."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, pygame"], ["Released", "itch.io, as Penumbra"]],
  },
  "thunder": {
    picture: "Arena vs AI over the coast: an F-16 at 855 km/h, a bandit high on the left, radar in search mode. Every pixel here is generated at runtime.",
    sections: [
      ["What it is", "A jet-combat arena for Unity 6 in a cel-shaded anime style with ink outlines. Four aircraft - F-16C, F-15C, MiG-29 and Su-27 - each with its own engines, transonic behaviour, inertia and loadout, and all with animated stabilators, flaperons, rudders and airbrakes."],
      ["Everything is procedural", "There are no imported assets. Every mesh, texture, sound, particle system and UI element is generated by code at runtime; open the project, press Play, fly. That was the constraint the whole project was built around."],
      ["The simulation", "A full ISA atmosphere, engines with altitude thrust lapse and ram drag, per-airframe critical Mach with wave-drag rise and Mach tuck, a fly-by-wire G and AoA limiter, and modular damage that degrades handling. Radar has SRC, PD, TWS, ACM and STT modes with a look-down notch; missiles are IR, SARH and ARH with pro-nav guidance and proximity fuzes. The AI detects missiles with its own sensors rather than omniscience."],
      ["Modes", "Campaign (four scripted missions per faction), Duel against a named ace, Arena vs AI with a ticket economy, Strike against a moving convoy or task force, an endless Gauntlet, and LAN / direct-IP multiplayer over Unity Netcode."],
    ],
    facts: [["Role", "Solo"], ["Stack", "C#, Unity 6 (URP), Netcode for GameObjects"], ["Status", "in progress - source private for now"]],
  },
  "sheet2tab": {
    picture: "A page of notation read into tablature, one bar wrong and flagged for the editor.",
    sections: [
      ["What it is", "Give it a PDF of a score and it hands back classical-guitar tablature under the notation, with an editor for the bars it misreads. It also transcribes from a recording or a video of a page, and can split the music between two, three or four guitars."],
      ["How it works", "PyMuPDF reads the page; a staff and note reader turns the pixels into pitches and durations; a fingering pass chooses strings and frets (lowest fret, lowest string, or most playable), a tuning that reaches the bass, and a capo if one helps. Output is engraved with LilyPond when it is installed and a built-in engraver when it is not, and can also be exported as MusicXML or MIDI."],
      ["Hearing it", "The editor plays the arrangement back with the moment being played marked in the tablature. A wrong pitch is far more obvious to the ear than to the eye, so playback turned out to be the quickest way to find the reader's mistakes."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, PyMuPDF, MusicXML, LilyPond"], ["Status", "in progress"]],
  },
  "chess-vision-bot": {
    picture: "The control panel, engine idle, waiting for a board to appear on screen.",
    sections: [
      ["What it is", "Watches a chessboard on your screen, rebuilds the position, and says what to play. It draws a line over the board for the suggested move and keeps an opening book for the first moves."],
      ["How it works", "A screen reader calibrated to the board's corners samples each square and matches it against the piece set; the position goes to an engine written in Python, which now has a C++ port for speed, and the suggested move is overlaid on the screen with PyQt5."],
      ["Where it is going", "The C++ engine is the current work: the Python one was fine for depth four and useless past it."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, PyQt5, python-chess, C++"], ["Status", "in progress"]],
  },
  "air-combat-sim": {
    sections: [
      ["What it is", "A flight-dynamics model in C++20 with a game on top of it. The simulation core is headless - atmosphere, aircraft, autopilot, and radar, IRST and RWR sensors - and has no rendering dependency, so it can be tested without a window."],
      ["Why deterministic", "The build disables fast-math and fixes floating-point contraction so a run replays identically on every machine. That makes the AI and the sensor models testable: the same inputs give the same flight, every time."],
      ["Structure", "core (vectors, quaternions, a seeded RNG, lookup tables), fdm (atmosphere, aircraft, autopilot), sensors, ai, sim, and data loaders for the aircraft definitions. Two executables: the game, and a headless runner for tests."],
    ],
    facts: [["Role", "Solo"], ["Stack", "C++20, CMake"], ["Status", "in progress"]],
  },
  "bladefall": {
    picture: "Level 1, one bot in view, the arena's stone cubes casting their shadow.",
    sections: [
      ["What it is", "A browser sword-arena .io game, playable on this site. Slash, stab, overhead and a special; parry and riposte; dash once you have earned it. Every kill without dying levels you up, the strongest fighter is crowned king, and dying resets you to level one."],
      ["How it is built", "TypeScript on a canvas, no engine. The world is a grid of pseudo-3D stone cubes; the fighters are circles with a sword, which turned out to read better than any sprite. The bots run the same combat rules as the player - same windups, same stamina, same parry window."],
      ["Design constants", "Everything that tunes the feel lives in one file: swing timings in milliseconds, movement multipliers while committed to an action, stamina regen and its delay, spawn protection. Changing the game is changing numbers."],
    ],
    facts: [["Role", "Solo"], ["Stack", "TypeScript, Canvas, Vite"], ["Status", "in progress"]],
  },
  "yt-grab": {
    picture: "The Download tab: a playlist URL, mp3 at 192 kbps, first ten items.",
    sections: [
      ["What it is", "A Windows app that downloads YouTube videos and playlists as mp3 or mp4, with a first-N-items option for playlists and a merge option that turns an album playlist into one file with a tracklist. A second tab plays the songs into a virtual microphone so a voice call hears the music instead of you."],
      ["How it is built", "One PowerShell file. The window is WPF, declared in XAML and parsed at startup; the downloading is yt-dlp and ffmpeg run as child processes with their output tailed into the log. The mic player uses NAudio to play into any output device and to mute the real microphone while a song is playing."],
      ["Details that mattered", "A pasted watch URL usually carries a list= parameter that is a YouTube Mix - related songs, not a playlist - so the app rewrites real playlist links to the playlist page and warns on mixes. Thumbnails are converted to JPEG before embedding, because the webp ones fail and get left beside the file."],
    ],
    facts: [["Role", "Solo"], ["Stack", "PowerShell 5.1, WPF, yt-dlp, ffmpeg, NAudio"], ["Status", "live"]],
  },
  "movegrade": {
    picture: "The panel after 5...Nxd5 in the Fried Liver: a mistake, the eval before and after, and the line the engine preferred.",
    sections: [
      ["What it is", "A Chrome extension for lichess and chess.com. After every move a badge says how good it was - Brilliant, Great, Best, Excellent, Good, Book, Inaccuracy, Mistake, Blunder - both in a small panel with its own board and eval bar, and pinned to the square on the site's board, the way chess.com's game review does it after the game. A dot per move along the bottom lets you go back to any earlier one."],
      ["How the grading works", "Stockfish 16 (the WebAssembly build, with the NNUE net) evaluates the position before the move with two principal variations, so it knows the best and second-best replies, and then the position after. Both evaluations become a win probability using lichess's formula, and the drop from the mover's side decides the category. Best is the engine's own move; Brilliant is a Best move that gives up material on purpose in a position that was not already won; Great is a Best move that was the only good one."],
      ["Depth, in stages", "Grading waits for nothing. Both positions are searched to depth four first and the badge appears from that - a fraction of a second - then every deeper iteration up to the depth you chose re-grades and updates it, with the badge drawn faintly until the search is done. Earlier moves are filled in in the background."],
      ["Where the engine lives", "Not in the panel. Both sites serve their pages cross-origin isolated (they need it for their own multithreaded Stockfish), and a Worker started from a frame embedded in such a page never loads. The engine therefore runs in an extension offscreen document that the sites cannot touch; panels talk to it over a runtime port, and one engine serves every open tab."],
      ["Reading the move list", "Lichess randomises the tag names in its move list, so there are no selectors to hold on to. The content script looks for the element that contains the most nodes that parse as chess notation and takes that as the move list; chess.com's list is a proper element, but writes piece letters as icons, so the figurine is folded back into the text."],
      ["Where it stays quiet", "In a live game against a person the panel shows Paused and does nothing. Real-time engine output in that game is engine assistance under either site's rules, and the point of this was to see what the engine thinks of a game, not to play it for you."],
    ],
    facts: [["Role", "Solo"], ["Stack", "JavaScript, Chrome MV3, Stockfish 16 WASM, chess.js"], ["Status", "live"]],
  },
  "durak": {
    picture: "A table open, a bout in progress.",
    sections: [
      ["What it is", "Durak - thirty-six cards, trump from the bottom of the deck, the last one holding cards loses. Two ways to play: against the machine, hidden behind the stack of cards in the corner of the home page, or against a friend on the online table."],
      ["Transfers", "Both games play perevodnoy durak. A defender who has not beaten anything yet may lay a card of the same rank beside the attack and hand the whole bout back; the attacker is now the defender. Only while everything on the table is unbeaten, only if the other side has enough cards to answer, never past six on the table. The machine transfers when it can."],
      ["How the online game works", "There is no server. One player hosts and reads out a six-letter code; the other joins with it and the two browsers talk directly over WebRTC (PeerJS handles the introduction). The host owns the game: every move from either side goes through the same rules function on the host, which then sends the whole state to both. The guest only proposes."],
      ["Why wordless", "The machine game has no copy at all - ranks and suits carry the state, two icon buttons carry the only two decisions, and the result is a stamp of suits or a skull. The online table allows itself one line, because you need to know whose move it is."],
    ],
    facts: [["Role", "Solo"], ["Stack", "JavaScript, WebRTC (PeerJS)"], ["Status", "live"]],
  },
  "yavalath-pentalath": {
    picture: "Yavalath in play: four in a row wins, three in a row loses.",
    sections: [
      ["What it is", "A-Level computer science coursework: Yavalath and Pentalath, two hex board games, in full - rules, sound, and a computer opponent. Yavalath was itself designed by a program, Cameron Browne's LUDI, which is what made it worth building."],
      ["The rules", "Four in a row wins, but three in a row loses - and that single twist makes a naive opponent throw the game. The AI searches a few plies with that in mind and prefers moves that force the other side into a losing three."],
      ["Documentation", "Written up to the exam board's format: analysis, design, technical solution, testing and evaluation. The document is linked from the index."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python"], ["For", "A-Level NEA"]],
  },
  "advent-of-code-2025": {
    sections: [
      ["What it is", "The December puzzles, one file a day, in Python. Nothing clever - the point was to do one every morning before anything else."],
    ],
    facts: [["Stack", "Python"]],
  },
  "project-euler": {
    sections: [
      ["What it is", "Solutions to the first hundred-odd Project Euler problems, in Python. Each one is on its own page: pick a number and read the code."],
      ["Run it here", "Every solution can be run in the browser - Pyodide loads a full CPython into a web worker, the input files are fetched alongside, and the output appears under the code with the time it took. Nothing is sent anywhere; the page does the computing."],
    ],
    facts: [["Stack", "Python"]],
  },
  "shooting-scores": {
    picture: "The rifle the scores came from: a Walther KK300.",
    sections: [
      ["What it is", "Plots a season of club shooting scores so you can see whether practice is working. Feed it the score sheets, get a chart of the trend, the spread, and the outliers."],
      ["How it is built", "Python and matplotlib, reading the club's spreadsheet format. Small, and used every week for a season."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, matplotlib"]],
  },
  "aimtrainer": {
    picture: "Click the circles before they go.",
    sections: [
      ["What it is", "The first thing made in pygame. Circles appear, you click them before they shrink away, and the score counts. Kept because it is where the games started."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, pygame"], ["Status", "early"]],
  },
  "this-website": {
    picture: "The front page.",
    sections: [
      ["What it is", "This site: Swiss editorial on black, static HTML, no build step. Every project in the index gets a page; the commit heatmap and the feed under it pull from GitHub in your browser."],
      ["How it is built", "Three fonts, two inks and a red. The project index is one array in script.js and every page is rendered from it; the Project Euler page is generated from the solution files. Previews are real screenshots, not renders."],
    ],
    facts: [["Role", "Solo"], ["Stack", "HTML, CSS, JavaScript"], ["Hosted", "GitHub Pages"]],
  },
  "yagi-uda-radar": {
    picture: "The 14.5 dBi Yagi-Uda on the bench.",
    sections: [
      ["What it is", "A 14.5 dBi Yagi-Uda antenna feeding RF transceivers off a Raspberry Pi 3 to range a target. Not finished - the antenna works, the ranging does not yet."],
      ["Where it came from", "CanSat. The telemetry link on the satellite was the first antenna built, and this is the one built afterwards to do it properly."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Raspberry Pi, RF transceivers, Python"], ["Status", "in progress"]],
  },
  "cansat-2025": {
    picture: "The team's CanSat, before the launch.",
    sections: [
      ["What it is", "A can-sized satellite for the CanSat competition, built by a team of seven at Tonbridge School through to a full critical design report. My part was the payload and the radio: the telemetry link and the antenna."],
      ["The report", "The critical design report is linked from the index: the mission, the payload, the ground station, and the test campaign."],
    ],
    facts: [["Role", "Payload and radio, team of seven"], ["Stack", "RF, telemetry"], ["Year", "2024-25"]],
  },
  "neural-scaling-laws": {
    picture: "The efficiency frontier: test loss against parameter count, one point per model.",
    sections: [
      ["What it is", "Multilayer perceptrons written from scratch in NumPy - no framework - trained at a range of sizes to see how test loss falls with parameter count. The library is on PyPI as elkwork; the paper is 56 pages."],
      ["Results", "98.52% on MNIST and 93.35% on FashionMNIST, and a clean power-law frontier once the models were trained to convergence. The interesting part was how much of the scaling story was really an optimiser story."],
      ["Companion", "The Drawer, below, is the same network reading a digit you draw, one layer at a time."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy, LaTeX"], ["Output", "paper, PyPI package"]],
  },
  "globular-clusters": {
    picture: "The N-body simulation, a few thousand steps in.",
    sections: [
      ["What it is", "Does a population of primordial binaries change how fast a globular cluster evaporates? An N-body simulation, a paper and a poster."],
      ["How it is built", "NumPy, direct summation with softening, and a leapfrog integrator. Runs were repeated with and without a binary population and the evaporation rate compared."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy"], ["Output", "paper, poster"]],
  },
  "drawer": {
    picture: "A drawn digit, and the network's read of it.",
    sections: [
      ["What it is", "A companion to the scaling-laws work: draw a digit and watch the trained network read it back, one layer at a time. Live handwritten digit recognition with the elkwork library."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy, elkwork"]],
  },
};

/* ---------- render ---------- */

(function () {
  const root = document.getElementById("case-copy");
  if (!root) return;

  const slug = new URLSearchParams(location.search).get("p") || "";
  const i = projects.findIndex((p) => slugFor(p) === slug);
  const p = projects[i];

  if (!p) {
    document.getElementById("case-title").textContent = "No such project";
    document.getElementById("case-setup").textContent = "Nothing in the index answers to “" + slug + "”.";
    return;
  }

  const c = CASES[slug] || { sections: [], facts: [] };

  document.title = p.title + " · Leonid Elkin";
  document.getElementById("case-idx").textContent = String(i + 1).padStart(2, "0") + " —";
  const h = document.getElementById("case-title");
  h.textContent = p.title;
  h.dataset.text = p.title;
  document.getElementById("case-setup").textContent = p.caption;

  const src = window.projectPreviewSrc && window.projectPreviewSrc(p.title);
  if (src) {
    const fig = document.getElementById("case-hero");
    document.getElementById("case-img").src = src;
    document.getElementById("case-img").alt = p.title;
    document.getElementById("case-cap").textContent = c.picture || "";
    fig.hidden = false;
  }

  (c.sections || []).forEach(([head, body], k) => {
    const h2 = el("h2", "display case-h");
    h2.textContent = head;
    root.appendChild(h2);
    root.appendChild(el("p", null, body));
  });
  if (!(c.sections || []).length) {
    root.appendChild(el("p", "placeholder", "[ Write-up to follow. The links on the right are the evidence for now. ]"));
  }

  const facts = document.getElementById("case-facts");
  const row = (k, v) => {
    const d = el("div");
    d.appendChild(el("dt", "k", k));
    const dd = el("dd");
    if (typeof v === "string") dd.textContent = v; else dd.appendChild(v);
    d.appendChild(dd);
    facts.appendChild(d);
  };
  if (p.status) row("Status", el("span", "status " + p.status, STATUS_LABEL[p.status]));
  (c.facts || []).forEach(([k, v]) => row(k, v));
  if (p.tags && p.tags.length) row("Tags", p.tags.join(", "));
  p.links.forEach((l) => row(l.name, linkEl(l)));

  const prev = projects[i - 1], next = projects[i + 1];
  const a1 = document.getElementById("case-prev"), a2 = document.getElementById("case-next");
  if (prev) { a1.href = pageFor(prev); a1.textContent = "← " + prev.title; } else a1.remove();
  if (next) { a2.href = pageFor(next); a2.textContent = next.title + " →"; } else a2.remove();
})();
