/* One page per project, all served by case.html?p=<slug>. The index entry
 * (title, caption, tags, links, status) comes from `projects` in script.js;
 * this file adds the write-up: a few short sections and the fact list.
 *
 * Slugs are made from the title (see slugFor in script.js). A project with no
 * entry here still gets a page - caption, picture, links - just no prose.
 */

const CASES = {
  "shellfall": {
    picture: "Day one of the campaign: the guns are laid, the first flotilla is in range.",
    sections: [
      ["What it is", "A coastal-defence game. You hold a fortress against a campaign of named capital ships. You place the guns yourself and mark what to hit, and the enemy keeps sailing. Released on itch.io under the name Penumbra."],
      ["How it is built", "Python and pygame. The ships, the fortress and the sea are drawn as sprites, and the campaign is scripted as a sequence of named engagements. A field manual inside the game explains the guns. A field-commands screen lets you give orders between salvos."],
      ["What it taught", "Pacing. The first builds let you fire as fast as you could click, and the whole thing collapsed into noise. Reload timers and named ships are what turned it into a game."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, pygame"], ["Released", "itch.io, as Penumbra"]],
  },
  "thunder": {
    picture: "Arena vs AI over the coast: an F-16 at 855 km/h, a bandit high on the left, radar in search mode. Every pixel here is generated at runtime.",
    sections: [
      ["What it is", "A jet-combat arena for Unity 6, cel-shaded with ink outlines. Four aircraft fly it: F-16C, F-15C, MiG-29 and Su-27. Each has its own engines, transonic behaviour, inertia and loadout, and all of them carry animated stabilators, flaperons, rudders and airbrakes."],
      ["Everything is procedural", "There are no imported assets. Every mesh, texture, sound, particle system and UI element is generated by code at runtime. Open the project, press Play, and fly. That was the constraint the whole project was built around, and everything else follows from it."],
      ["The simulation", "A full ISA atmosphere, engines with altitude thrust lapse and ram drag, and per-airframe critical Mach with wave-drag rise and Mach tuck. A fly-by-wire limiter holds G and AoA, and modular damage degrades handling as it accumulates. Radar has SRC, PD, TWS, ACM and STT modes with a look-down notch. Missiles are IR, SARH and ARH, with pro-nav guidance and proximity fuzes. The AI detects them with its own sensors rather than by omniscience."],
      ["Modes", "Campaign runs four scripted missions per faction. Duel puts you against a named ace, Arena vs AI runs a ticket economy, and Strike sends you at a moving convoy or task force. Gauntlet is endless. Multiplayer is LAN or direct IP over Unity Netcode."],
      ["What is next", "Netcode. The arena stays single-player until the aircraft state replicates cleanly. Spawn points and biomes were the last things rewritten. The source and a Windows build follow once a match between two machines holds together for ten minutes."],
    ],
    facts: [["Role", "Solo"], ["Stack", "C#, Unity 6 (URP), Netcode for GameObjects"]],
  },
  "fuguesplit": {
    picture: "BWV 544 dealt out: Guitar I keeping the top line, Guitar II underneath it, one note at a time and nothing stacked.",
    sections: [
      ["What it is", "A converter that turns a fugue into a band. Give it an organ score and it hands back one part per player, two or three guitars and a bass, each strictly one note at a time. Output is a Guitar Pro file, and for the organ works a printed part per player as well, notation over tablature. 3,445 movements of Bach are published this way, four Vivaldi arias beside them, and one fugue the program wrote itself."],
      ["Why a fugue", "Because a fugue is already the answer. Most arranging for guitar means taking chords apart and guessing which notes were the tune. A fugue is written as independent melodic lines that happen to sound at once, so the music has already done the separating. The job is only to work out which line is which and hand each one to a player. Everything the program does well, it does because the source is contrapuntal."],
      ["Who plays what", "That turns out to be an assignment problem, and it is the whole of the interesting part. At every onset the cost of putting a note on a part blends four preferences: keep a part near the pitch it just played, keep Guitar I above Guitar II, do not cut off a note still sounding, and honour the source file's own track separation. It is solved exactly, with a small Hungarian solver, rather than greedily. A chord is therefore dealt out as a whole instead of first-come-first-served. Continuity decays with silence, so a part that has rested for two beats is free to pick the music up wherever it is needed."],
      ["The band grows with the music", "A fugue does not hold still. BWV 582 opens in three voices and later stacks five over the pedal. A note that arrives when every player is busy gets written into the stave's second voice, where Guitar Pro greys it out. Wherever that grey appears, another guitar is added and the piece is dealt out again, until nothing is left greyed. A fifth cost term ranks the guitars: whenever a part would fall silent it gets a discount for picking a note up, largest for the lead and tapering to nothing for the last. Guitar I therefore carries an unbroken line and the others fill in around it. On BWV 544 that takes the lead from 80% of the piece to 96%."],
      ["Sparing the bassist", "An organ pedal line transcribed literally sends a bass guitar a long way up the neck: 17.7% of bass notes above the 12th fret, and 36% in the worst piece. So the bass is folded against a comfortable fret span rather than the whole neck, and its fingering is pinned there too. Anything still too high is handed to a guitar that happens to be silent. Across all thirty Bach preludes and fugues that puts every one of 17,328 bass notes at or below the 12th fret. Before this stage the output was correct – and no bassist would have agreed to read it."],
      ["Finishing Contrapunctus XIV", "Bach's last fugue stops mid-bar, 239 bars in. The program completes it out of his own material – the four subjects, which it has to find in his text before it can use them. The joins are where he put them. It is arithmetic rather than inspiration, and the write-up says so. Every note in the completion is Bach's."],
      ["Writing one instead", "The step after that was to stop borrowing. fugue3.py writes an original three-voice fugue in E minor, thirty bars for two guitars and a bass. It hands the result to the same arranger as everything else, so it comes out as a tab with the rest. Authored: a fourteen-note subject and the plan of entries. Derived: the answer, the countersubject, every free voice and every episode. Each is searched by a Viterbi pass over the diatonic pitches in the part's compass, with counterpoint as the emission cost and melodic interval as the transition. It scores 100% on the same chord test Bach's Contrapunctus XIV scores 74% on. That figure is a limitation rather than a boast: a search told dissonance is expensive buys none, so there are no suspensions. Bach's other 26% is where those live."],
      ["A bug worth naming", "The fine for parallel fifths measured the interval as a signed remainder. An interval between two voices is a distance, so it has to be measured with an absolute value. Signed, it calls a fifth below a fourth, and lets through every parallel in which the moving voice is the lower one. Written that way the piece had three parallel fifths and passed its own test. Measured properly it has none, nor a crossing, nor a note outside a part's compass."],
      ["What is not solved", "Binary rhythms only: a source with triplets is quantised onto the nearest grid. Playability is positional rather than physical, so the fretting solver minimises hand movement without modelling finger stretch, and a dense passage can still ask for an awkward shape. Reading a piece off a printed page is a draft. Roughly one note in eleven comes back wrong or missing even from a clean PDF, and one misread bar moves every bar line after it, so it says to proofread before playing. Ornaments marked in an engraving stay symbols and never become notes."],
      ["Checking it", "159 tests. The assignment solver is checked against brute-force optimality. The notation layer is checked exhaustively, every offset and length on a 32nd grid in both simple and compound metre. End-to-end tests parse the written .gp5 back and assert that every bar is exactly filled, every beat holds at most one note, and every fret lies within the tuning. A separate verifier traces each written note back to the note it came from, and is itself checked against a tab with a note deliberately altered in the file."],
    ],
    facts: [
      ["Role", "Solo"],
      ["Stack", "Python, PyGuitarPro, mido, MuseScore"],
      ["Published", "3,450 movements, 30 shelves"],
      ["Licence", "CC BY-NC-SA 4.0, after the source engravings"],
    ],
  },
  "sheet2tab": {
    picture: "A page of notation read into tablature, one bar wrong and flagged for the editor.",
    sections: [
      ["What it is", "Give it a PDF of a score and it hands back classical-guitar tablature under the notation, with an editor for the bars it misreads. It also transcribes from a recording or a video of a page, and can split the music between two, three or four guitars."],
      ["How it works", "PyMuPDF reads the page. A staff and note reader turns the pixels into pitches and durations. A fingering pass then chooses strings and frets (lowest fret, lowest string, or most playable), a tuning that reaches the bass, and a capo where one helps. Output is engraved with LilyPond where it is installed and with a built-in engraver where it is not, and can also be exported as MusicXML or MIDI."],
      ["Hearing it", "The editor plays the arrangement back with the moment being played marked in the tablature. A wrong pitch is far more obvious to the ear than to the eye – so playback turned out to be the quickest way to find the reader's mistakes."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, PyMuPDF, MusicXML, LilyPond"]],
  },
  "chess-vision-bot": {
    picture: "The control panel, engine idle, waiting for a board to appear on screen.",
    sections: [
      ["What it is", "Watches a chessboard on your screen, rebuilds the position, and says what to play. It draws a line over the board for the suggested move and keeps an opening book for the first moves."],
      ["How it works", "A screen reader calibrated to the board's corners samples each square and matches it against the piece set. The position then goes to an engine written in Python, which now has a C++ port for speed. The suggested move is overlaid on the screen with PyQt5."],
      ["What is next", "The C++ engine is the current work. The Python one was fine to depth four and useless past it, so it is being ported move for move against the original, and the detector stays in Python. MoveGrade, the extension on this site, grew out of the same detector. The browser version reads the move list instead of the screen."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, PyQt5, python-chess, C++"]],
  },
  "air-combat-sim": {
    sections: [
      ["What it is", "A flight-dynamics model in C++20 with a game on top of it. The simulation core is headless: atmosphere, aircraft, autopilot, and radar, IRST and RWR sensors. It has no rendering dependency, so it can be tested without a window."],
      ["Why deterministic", "The build disables fast-math and fixes floating-point contraction so a run replays identically on every machine. That makes the AI and the sensor models testable: the same inputs give the same flight, every time."],
      ["Structure", "core (vectors, quaternions, a seeded RNG, lookup tables), fdm (atmosphere, aircraft, autopilot), sensors, ai, sim, and data loaders for the aircraft definitions. Two executables: the game, and a headless runner for tests."],
    ],
    facts: [["Role", "Solo"], ["Stack", "C++20, CMake"]],
  },
  "yt-grab": {
    /* No picture: the file that was here showed a different program
       entirely. A caption is added back with the screenshot. */
    sections: [
      ["What it is", "A Windows app that downloads YouTube videos and playlists as mp3 or mp4. Playlists get a first-N-items option, and a merge option that turns an album playlist into one file with a tracklist. A second tab plays the songs into a virtual microphone, so a voice call hears the music instead of you."],
      ["How it is built", "One PowerShell file. The window is WPF, declared in XAML and parsed at startup. Downloading is yt-dlp and ffmpeg, run as child processes with their output tailed into the log. The mic player uses NAudio to play into any output device, and to mute the real microphone while a song is playing."],
      ["Details that mattered", "A pasted watch URL usually carries a list= parameter that is a YouTube Mix, which is related songs rather than a playlist. So the app rewrites real playlist links to the playlist page, and warns on mixes. Thumbnails are converted to JPEG before embedding, because the webp ones fail and get left beside the file."],
      ["What broke", "YouTube started answering 403 to every download. The fix was yt-dlp's JavaScript challenge solver – which needs deno on the machine – so the app now checks for it on start. Radio-style mixes are open-ended, so the merge is capped rather than allowed to run all night."],
    ],
    facts: [["Role", "Solo"], ["Stack", "PowerShell 5.1, WPF, yt-dlp, ffmpeg, NAudio"]],
  },
  "movegrade": {
    picture: "The panel after 5...Nxd5 in the Fried Liver: a mistake, the eval before and after, and the line the engine preferred.",
    sections: [
      ["What it is", "A Chrome extension for lichess and chess.com. After every move a badge says how good it was: Brilliant, Great, Best, Excellent, Good, Book, Forced, Inaccuracy, Mistake, Miss or Blunder. It appears twice, in a small panel with its own board and eval bar, and pinned to the square on the site's board, the way chess.com's game review does it after the game. A dot per move along the bottom takes you back to any earlier one."],
      ["How the grading works", "Stockfish 16, the WebAssembly build with the NNUE net, evaluates the position before the move with two principal variations, so it knows the best and second-best replies. It then evaluates the position after. Both evaluations become a win probability using lichess's formula, and the drop from the mover's side decides the category. The bands are chess.com's published Expected Points figures rather than numbers of my own – 2, 5, 10 and 20 percentage points – because that is the scale players already recognise. Lichess grades far more leniently. Best is the engine's own move and reports no loss at all, since the move the engine wanted cannot have lost anything. Brilliant is a Best move that gives up material on purpose in a position that was not already won. Great is a Best move that was the only good one, and Forced is a move that was the only legal one, where there is nothing to grade. Miss runs the other way: a mate or a won position was there and the move played does not keep it, so the badge names the chance rather than the size of the drop."],
      ["Openings are a database question", "A gambit gives away a pawn, so the engine marks it down, so the Smith-Morra used to come out as an Inaccuracy. That is nonsense: it is theory. Book is decided by a database now instead of by the eval, covering every position of 3,328 named openings, 7,853 positions in all, taken from the ECO tables lichess publishes. Positions are keyed by the board rather than by the move order, so a line that transposes into theory still counts as theory. A move is Book while the game has not left that book and the move has not left the player clearly worse. That second half is what stops a name on a line from excusing everything played in it. The Damiano Defence keeps the badge while it is merely dubious, and loses it at the move that actually drops the pawn. The name of the opening sits under the badge whatever the grade is, and stays there, dimmed, once the game leaves book."],
      ["A clock rather than a depth", "The book is consulted before the engine is asked anything at all, so a theory move carries its badge from the moment it appears. It used to spend a third of a second called an inaccuracy while a shallow search caught up. Everything else is searched on a clock. A fixed depth costs whatever the position happens to cost – instant in a bare ending, many seconds in a sharp middlegame with six pieces hanging – so the badge used to arrive whenever it felt like it and the number on the slider meant nothing you could feel. Every move now gets the same wall clock, a second by default, and the engine goes as deep as that position allows: around depth 14 in one second, past 20 if you give it three. The badge is drawn faintly and re-graded as the search deepens, and earlier moves are filled in behind it."],
      ["Where the engine lives", "Outside the panel. Both sites serve their pages cross-origin isolated (they need it for their own multithreaded Stockfish), and a Worker started from a frame embedded in such a page never loads. The engine therefore runs in an extension offscreen document that the sites cannot touch. Panels talk to it over a runtime port, and one engine serves every open tab."],
      ["Reading the move list", "Lichess randomises the tag names in its move list, so there are no selectors to hold on to. The content script looks for the element containing the most nodes that parse as chess notation, and takes that as the move list. Chess.com's list is a proper element, but writes piece letters as icons, so the figurine is folded back into the text."],
      ["Where it stays quiet", "In a live game against a person the panel shows Paused and does nothing. Real-time engine output in that game is engine assistance under either site's rules. The point of this was to see what the engine thinks of a game you are watching or reviewing."],
      ["What broke, what is next", "The first build put the engine inside the panel and it never started. Both sites cross-origin-isolate their pages, so the Worker refused to load with an empty error – a day of diagnosis for a one-line cause. Next: the chess.com live-game detection is written from the DOM of the analysis board and needs a real logged-in game to prove it. The 40 MB net should be fetched once and cached rather than shipped. A puzzle mode that hides the grade until you have chosen your own move is the other thing on the list."],
    ],
    facts: [["Role", "Solo"], ["Stack", "JavaScript, Chrome MV3, Stockfish 16 WASM, chess.js"]],
  },
  "durak": {
    picture: "A table open, a bout in progress.",
    sections: [
      ["What it is", "Durak: thirty-six cards, trump from the bottom of the deck, and the last player holding cards loses. There are two ways to play. Against the machine, hidden behind the stack of cards in the corner of the home page, or against a friend on the online table."],
      ["Transfers", "Both games play perevodnoy durak. A defender who has not beaten anything yet may lay a card of the same rank beside the attack and hand the whole bout back, and the attacker is now the defender. It works only while everything on the table is unbeaten, only if the other side has enough cards to answer, and never past six on the table. The machine transfers whenever it can."],
      ["How the online game works", "There is no server. One player hosts and reads out a six-letter code. The other joins with it, and the two browsers talk directly over WebRTC (PeerJS handles the introduction). The host owns the game: every move from either side goes through the same rules function on the host, which then sends the whole state to both. The guest only proposes."],
      ["Why wordless", "The machine game has no copy at all. Ranks and suits carry the state, two icon buttons carry the only two decisions, and the result is a stamp of suits or a skull. The online table allows itself one line, because you need to know whose move it is."],
      ["What broke", "WebRTC with STUN alone works between two homes and fails behind anything that rewrites addresses – a corporate proxy, some VPNs. A TURN relay fixes it, and needs a metered key on the host. That is the reason there is still no server: adding a relay would make it the first one. The machine also still plays every transfer it can, which a person would not."],
    ],
    facts: [["Role", "Solo"], ["Stack", "JavaScript, WebRTC (PeerJS)"]],
  },
  "yavalath-pentalath": {
    picture: "Yavalath in play: four in a row wins, three in a row loses.",
    sections: [
      ["What it is", "A-Level computer science coursework: Yavalath and Pentalath, two hex board games, in full. Rules, sound, and a computer opponent. Yavalath was itself designed by a program, Cameron Browne's LUDI, which is what made it worth building."],
      ["The rules", "Four in a row wins and three in a row loses. That single twist makes a naive opponent throw the game. The AI searches a few plies with it in mind, and prefers moves that force the other side into a losing three."],
      ["Documentation", "Written up to the exam board's format: analysis, design, technical solution, testing and evaluation. The document is linked from the index."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python"], ["For", "A-Level NEA"]],
  },
  "advent-of-code-2025": {
    sections: [
      ["What it is", "The December puzzles, one file a day, in Python. Nothing clever. The point was to do one every morning before anything else."],
    ],
    facts: [["Stack", "Python"]],
  },
  "project-euler": {
    sections: [
      ["What it is", "Solutions to the first hundred-odd Project Euler problems, in Python. Each one is on its own page: pick a number and read the code."],
      ["Run it here", "Every solution can be run in the browser. Pyodide loads a full CPython into a web worker, the input files are fetched alongside, and the output appears under the code with the time it took. Nothing is sent anywhere, because the page does the computing."],
    ],
    facts: [["Stack", "Python"]],
  },
  "shooting-scores": {
    picture: "The rifle the scores came from: a Walther KK300.",
    sections: [
      ["What it is", "Plots a season of club shooting scores so you can see whether practice is working. Feed it the score sheets, get a chart of the trend, the spread, and the outliers."],
      ["How it is built", "Python and matplotlib, reading the club's spreadsheet format. Small, and used every week for a season."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, matplotlib"]],
  },
  "aimtrainer": {
    picture: "Click the circles before they go.",
    sections: [
      ["What it is", "The first thing made in pygame. Circles appear, you click them before they shrink away, and the score counts. Kept because it is where the games started."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, pygame"]],
  },
  "this-website": {
    picture: "The front page.",
    sections: [
      ["What it is", "This site: Swiss editorial on black, static HTML, no build step. Every project in the index gets a page. The commit heatmap and the feed under it pull from GitHub in your browser."],
      ["How it is built", "Three fonts, two inks and a red. The project index is one array in script.js, and every page is rendered from it. The Project Euler page is generated from the solution files. Previews are real screenshots rather than renders."],
    ],
    facts: [["Role", "Solo"], ["Stack", "HTML, CSS, JavaScript"], ["Hosted", "GitHub Pages"]],
  },
  "yagi-uda-radar": {
    picture: "The 14.5 dBi Yagi-Uda on the bench.",
    sections: [
      ["What it is", "A 14.5 dBi Yagi-Uda antenna feeding RF transceivers off a Raspberry Pi 3 to range a target. The antenna works and the ranging does not yet."],
      ["Where it came from", "CanSat. The telemetry link on the satellite was the first antenna built, and this is the one built afterwards to do the job properly."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Raspberry Pi, RF transceivers, Python"]],
  },
  "cansat-2025": {
    picture: "The team's CanSat, before the launch.",
    sections: [
      ["What it is", "A can-sized satellite for the CanSat competition, built by a team of seven at Tonbridge School through to a full critical design report. My part was the payload and the radio: the telemetry link and the antenna."],
      ["The report", "The critical design report is linked from the index: the mission, the payload, the ground station, and the test campaign."],
    ],
    facts: [["Role", "Payload and radio, team of seven"], ["Stack", "RF, telemetry"], ["Year", "2024-25"]],
  },
  "neural-scaling-laws": {
    picture: "The efficiency frontier: test loss against parameter count, one point per model.",
    sections: [
      ["What it is", "Multilayer perceptrons written from scratch in NumPy – no framework – trained at a range of sizes to measure how test loss falls with parameter count. The library is on PyPI as elkwork, and the paper runs to 56 pages."],
      ["Results", "98.52% on MNIST and 93.35% on FashionMNIST, and a clean power-law frontier once the models were trained to convergence. The interesting part was how much of the scaling story was really an optimiser story."],
      ["Companion", "The Drawer, below, is the same network reading a digit you draw, one layer at a time."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy, LaTeX"], ["Output", "paper, PyPI package"]],
  },
  "globular-clusters": {
    picture: "The N-body simulation, a few thousand steps in.",
    sections: [
      ["What it is", "Does a population of primordial binaries change how fast a globular cluster evaporates? An N-body simulation, a paper and a poster."],
      ["How it is built", "NumPy, direct summation with softening, and a leapfrog integrator. Runs were repeated with and without a binary population and the evaporation rate compared."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy"], ["Output", "paper, poster"]],
  },
  "drawer": {
    picture: "A drawn digit, and the network's read of it.",
    sections: [
      ["What it is", "A companion to the scaling-laws work: draw a digit and watch the trained network read it back, one layer at a time. Live handwritten digit recognition with the elkwork library."],
    ],
    facts: [["Role", "Solo"], ["Stack", "Python, NumPy, elkwork"]],
  },
};

/* ---------- render ---------- */

(function () {
  const root = document.getElementById("case-copy");
  if (!root) return;

  const slug = new URLSearchParams(location.search).get("p") || "";
  const i = projects.findIndex((p) => slugFor(p) === slug);
  const p = projects[i];

  if (!p) {
    document.getElementById("case-title").textContent = "No such project";
    document.getElementById("case-setup").textContent = "Nothing in the index answers to “" + slug + "”.";
    return;
  }

  const c = CASES[slug] || { sections: [], facts: [] };

  document.title = p.title + " · Leonid Elkin";
  document.getElementById("case-idx").textContent = String(i + 1).padStart(2, "0") + " –";
  const h = document.getElementById("case-title");
  h.textContent = p.title;
  h.dataset.text = p.title;
  document.getElementById("case-setup").textContent = p.caption;

  const src = window.projectPreviewSrc && window.projectPreviewSrc(p.title);
  if (src) {
    // per-project share image (for the scrapers that run scripts)
    const og = document.querySelector('meta[property="og:image"]');
    if (og) og.content = new URL(src, location.href).href;
    const fig = document.getElementById("case-hero");
    document.getElementById("case-img").src = src;
    document.getElementById("case-img").hidden = false;
    document.getElementById("case-img").alt = p.title;
    document.getElementById("case-cap").textContent = c.picture || "";
    fig.hidden = false;
  }

  (c.sections || []).forEach(([head, body], k) => {
    const h2 = el("h2", "display case-h");
    h2.textContent = head;
    root.appendChild(h2);
    root.appendChild(el("p", null, body));
  });
  if (slug === "movegrade" && window.mountMoveGradeDemo) window.mountMoveGradeDemo(root);
  if (!(c.sections || []).length) {
    root.appendChild(el("p", "placeholder", "[ Write-up to follow. The links on the right are the evidence for now. ]"));
  }

  const facts = document.getElementById("case-facts");
  const row = (k, v) => {
    const d = el("div");
    d.appendChild(el("dt", "k", k));
    const dd = el("dd");
    if (typeof v === "string") dd.textContent = v; else dd.appendChild(v);
    d.appendChild(dd);
    facts.appendChild(d);
  };
  if (p.status) row("Status", el("span", "status " + p.status, STATUS_LABEL[p.status]));
  (c.facts || []).forEach(([k, v]) => row(k, v));
  /* Tags and the Stack fact say the same thing - identically on nine of the
     twenty pages, and on the rest Stack is simply the more precise of the two
     ("PowerShell 5.1" against "PowerShell"). Print Tags only where the write-up
     gives no Stack, so the list never repeats itself. The tags still drive the
     index filter and the chips on the card. */
  const hasStack = (c.facts || []).some((f) => f[0] === "Stack");
  if (!hasStack && p.tags && p.tags.length) row("Tags", p.tags.join(", "));
  p.links.forEach((l) => row(l.name, linkEl(l)));

  const prev = projects[i - 1], next = projects[i + 1];
  const a1 = document.getElementById("case-prev"), a2 = document.getElementById("case-next");
  if (prev) { a1.href = pageFor(prev); a1.textContent = "← " + prev.title; } else a1.remove();
  if (next) { a2.href = pageFor(next); a2.textContent = next.title + " →"; } else a2.remove();
})();
